kind: Service
apiVersion: v1
metadata:
  name: awsclb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
  - port: 80
    targetPort: 30001
    protocol: TCP
    name: http
  - port: 443
    targetPort: 30002
    protocol: TCP
    name: https
  externalTrafficPolicy: Cluster
